apiVersion: v1
kind: Pod
metadata:
  name: {POD_NAME}
  labels:
    # Used for Pod anti-affinity.
    krun: pod
spec:
  # Tells Kubernetes to try to not schedule this Pod on the same node as other
  # instances of this Pod.
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: krun
              operator: In
              values:
              - pod
          topologyKey: kubernetes.io/hostname
  containers:
  - name: container
    # The image should contain bash at least.
    image: {POD_IMAGE}
    imagePullPolicy: Always
    command:
    # Always tries to use the bash from the user environment.
    - /usr/bin/env
    - bash
    - --rcfile
    - /krun/.bashrc
    env:
    - name: HISTFILE
      value: /krun/.bash_history
    # Synchronizes the history after every command.
    - name: PROMPT_COMMAND
      value: history -a;history -c;history -r
    # This allows for the container to be attached to.
    stdin: true
    tty: true
    volumeMounts:
    - name: nfs
      mountPath: /krun
    workingDir: /krun
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
