apiVersion: v1
kind: Pod
metadata:
  name: {POD_NAME}
  labels:
    app: nfs-test
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nfs-test
          topologyKey: kubernetes.io/hostname
  containers:
  - name: container
    image: {POD_IMAGE}
    imagePullPolicy: Always
    command:
    - /usr/bin/env
    - bash
    - --rcfile
    - /krun/.bashrc
    env:
    - name: HISTFILE
      value: /krun/.bash_history
    # Synchronize the history for every command
    - name: PROMPT_COMMAND
      value: history -a;history -c;history -r
    stdin: true
    tty: true
    volumeMounts:
    - name: nfs
      mountPath: /krun
    workingDir: /krun
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
