apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    # Have this match the size of the disk.
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    # The NFS service backing this PV.
    server: nfs-server.krun.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      # Have this match the size of the disk.
      storage: 10Gi
